fix: Switch to patched version of zephyr
This is to resolve errors building my config with leader keys:
ERROR: /behaviors/fr_leader POST_KERNEL 13 < /behaviors/fr_e_acute POST_KERNEL 22